#!/bin/bash

./replace-chain-id 1 && graph build --network mainnet && graph deploy --product hosted-service railgun-community/railgun-v2-ethereum; \
./replace-chain-id 5 && graph build --network goerli && graph deploy --product hosted-service railgun-community/railgun-v2-goerli; \
./replace-chain-id 56 && graph build --network bsc && graph deploy --product hosted-service railgun-community/railgun-v2-bsc; \
./replace-chain-id 137 && graph build --network matic && graph deploy --product hosted-service railgun-community/railgun-v2-polygon; \
./replace-chain-id 80001 && graph build --network mumbai && graph deploy --product hosted-service railgun-community/railgun-v2-mumbai; \
./replace-chain-id 42161 && graph build --network arbitrum-one && graph deploy --product hosted-service railgun-community/railgun-v2-arbitrum; \
./replace-chain-id 421613 && graph build --network arbitrum-goerli && graph deploy --product hosted-service railgun-community/railgun-v2-arbitrum-goerli;

# Reset
./replace-chain-id 1